/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseSelect: typeof import('./src/components/UI/BaseSelect.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    component: typeof import('vue')['component']
    IconSprite: typeof import('./src/components/UI/IconSprite.vue')['default']
    ListBreeds: typeof import('./src/components/ListBreeds.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
